package ru.alisuner.app.ui.screens

import android.media.MediaPlayer
import android.os.Environment
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalFocusManager
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.Job
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import ru.alisuner.app.api.HuggingFaceService
import ru.alisuner.app.api.MusicGenRequest
import ru.alisuner.app.api.MusicGenParameters
import java.io.DataOutputStream
import java.io.File
import kotlin.math.abs
import kotlin.math.pow

/**
 * Аранжировщик с бесплатным AI (Hugging Face).
 *
 * Генерирует музыку по текстовому описанию через facebook/musicgen-small.
 * Полностью бесплатно, без API ключей.
 */
@Composable
fun ArrangerScreen() {
    val context = LocalContext.current
    val focusManager = LocalFocusManager.current
    val scope = rememberCoroutineScope()

    // ── Промпт ──
    var melodyPrompt by remember { mutableStateOf("") }

    // ── Статус ──
    var status by remember { mutableStateOf("") }
    var audioFilePath by remember { mutableStateOf<String?>(null) }
    var isGenerating by remember { mutableStateOf(false) }
    var generationJob by remember { mutableStateOf<Job?>(null) }
    var mediaPlayer by remember { mutableStateOf<MediaPlayer?>(null) }
    var isPlayingGenerated by remember { mutableStateOf(false) }

    // ── Длительность ──
    var duration by remember { mutableIntStateOf(8) } // секунды

    fun stopGeneratedPlayback() {
        mediaPlayer?.let { player ->
            runCatching {
                if (player.isPlaying) player.stop()
            }
            player.release()
        }
        mediaPlayer = null
        isPlayingGenerated = false
    }

    fun playGeneratedTrack(path: String) {
        if (isPlayingGenerated) {
            stopGeneratedPlayback()
            status = "Воспроизведение остановлено"
            return
        }

        try {
            stopGeneratedPlayback()
            val player = MediaPlayer().apply {
                setDataSource(path)
                setOnCompletionListener {
                    it.release()
                    if (mediaPlayer === it) mediaPlayer = null
                    isPlayingGenerated = false
                    status = "Воспроизведение завершено"
                }
                setOnErrorListener { mp, _, _ ->
                    mp.release()
                    if (mediaPlayer === mp) mediaPlayer = null
                    isPlayingGenerated = false
                    status = "Не удалось воспроизвести файл"
                    true
                }
                prepare()
                start()
            }
            mediaPlayer = player
            isPlayingGenerated = true
            status = "Воспроизведение..."
        } catch (e: Exception) {
            stopGeneratedPlayback()
            status = "Ошибка воспроизведения: ${e.message}"
        }
    }

    fun writeAscii(output: DataOutputStream, value: String) {
        output.write(value.toByteArray(Charsets.US_ASCII))
    }

    fun writeLittleEndianShort(output: DataOutputStream, value: Int) {
        output.writeByte(value and 0xFF)
        output.writeByte((value shr 8) and 0xFF)
    }

    fun writeLittleEndianInt(output: DataOutputStream, value: Int) {
        output.writeByte(value and 0xFF)
        output.writeByte((value shr 8) and 0xFF)
        output.writeByte((value shr 16) and 0xFF)
        output.writeByte((value shr 24) and 0xFF)
    }

    fun writeWavFile(file: File, samples: ShortArray, sampleRate: Int) {
        val dataSize = samples.size * 2
        DataOutputStream(file.outputStream().buffered()).use { output ->
            writeAscii(output, "RIFF")
            writeLittleEndianInt(output, 36 + dataSize)
            writeAscii(output, "WAVEfmt ")
            writeLittleEndianInt(output, 16)
            writeLittleEndianShort(output, 1)
            writeLittleEndianShort(output, 1)
            writeLittleEndianInt(output, sampleRate)
            writeLittleEndianInt(output, sampleRate * 2)
            writeLittleEndianShort(output, 2)
            writeLittleEndianShort(output, 16)
            writeAscii(output, "data")
            writeLittleEndianInt(output, dataSize)
            samples.forEach { sample -> writeLittleEndianShort(output, sample.toInt()) }
        }
    }

    fun createOfflineArrangement(prompt: String, lengthSeconds: Int): File {
        val sampleRate = 44100
        val totalSamples = sampleRate * lengthSeconds
        val mix = DoubleArray(totalSamples)
        val musicDir = context.getExternalFilesDir(Environment.DIRECTORY_MUSIC) ?: context.filesDir
        val audioFile = File(musicDir, "offline_arrangement_${System.currentTimeMillis()}.wav")

        data class GuitarSample(
            val midiNote: Int,
            val sourceRate: Int,
            val pcm: DoubleArray
        )

        fun readLittleEndianInt(bytes: ByteArray, offset: Int): Int =
            (bytes[offset].toInt() and 0xFF) or
                ((bytes[offset + 1].toInt() and 0xFF) shl 8) or
                ((bytes[offset + 2].toInt() and 0xFF) shl 16) or
                ((bytes[offset + 3].toInt() and 0xFF) shl 24)

        fun readLittleEndianShort(bytes: ByteArray, offset: Int): Int =
            (bytes[offset].toInt() and 0xFF) or ((bytes[offset + 1].toInt() and 0xFF) shl 8)

        fun midiFromFileName(fileName: String): Int {
            val match = Regex("""^([A-G])(#?)(-?\d+)\.wav$""").matchEntire(fileName)
                ?: error("Unknown guitar sample name: $fileName")
            val base = when (match.groupValues[1]) {
                "C" -> 0
                "D" -> 2
                "E" -> 4
                "F" -> 5
                "G" -> 7
                "A" -> 9
                else -> 11
            }
            val accidental = if (match.groupValues[2] == "#") 1 else 0
            val octave = match.groupValues[3].toInt()
            return (octave + 1) * 12 + base + accidental
        }

        fun readWavSample(fileName: String): GuitarSample {
            val bytes = context.assets.open("freepats_guitar/$fileName").use { it.readBytes() }
            var offset = 12
            var sourceRate = 44100
            var channels = 1
            var bitsPerSample = 16
            var dataOffset = -1
            var dataSize = 0

            while (offset + 8 <= bytes.size) {
                val chunkId = String(bytes, offset, 4, Charsets.US_ASCII)
                val chunkSize = readLittleEndianInt(bytes, offset + 4)
                val chunkDataOffset = offset + 8
                when (chunkId) {
                    "fmt " -> {
                        channels = readLittleEndianShort(bytes, chunkDataOffset + 2).coerceAtLeast(1)
                        sourceRate = readLittleEndianInt(bytes, chunkDataOffset + 4)
                        bitsPerSample = readLittleEndianShort(bytes, chunkDataOffset + 14)
                    }
                    "data" -> {
                        dataOffset = chunkDataOffset
                        dataSize = chunkSize
                    }
                }
                offset = chunkDataOffset + chunkSize + (chunkSize and 1)
            }

            require(dataOffset >= 0 && bitsPerSample == 16) { "Unsupported WAV sample: $fileName" }

            val frameCount = dataSize / (channels * 2)
            val pcm = DoubleArray(frameCount)
            for (frame in 0 until frameCount) {
                var sum = 0
                for (channel in 0 until channels) {
                    val sampleOffset = dataOffset + (frame * channels + channel) * 2
                    val raw = readLittleEndianShort(bytes, sampleOffset)
                    val signed = if (raw > Short.MAX_VALUE) raw - 65536 else raw
                    sum += signed
                }
                pcm[frame] = (sum / channels.toDouble()) / Short.MAX_VALUE
            }
            return GuitarSample(midiFromFileName(fileName), sourceRate, pcm)
        }

        val guitarSamples = context.assets.list("freepats_guitar")
            .orEmpty()
            .filter { it.endsWith(".wav", ignoreCase = true) }
            .map(::readWavSample)
            .sortedBy { it.midiNote }

        require(guitarSamples.isNotEmpty()) { "Гитарные сэмплы не найдены" }

        fun addSampledNote(startSample: Int, targetMidi: Int, velocity: Double) {
            if (startSample !in mix.indices) return
            val sample = guitarSamples.minBy { abs(it.midiNote - targetMidi) }
            val pitchRatio = 2.0.pow((targetMidi - sample.midiNote) / 12.0)
            val sourceStep = pitchRatio * sample.sourceRate / sampleRate
            var sourcePosition = 0.0
            var outputIndex = startSample

            while (outputIndex < mix.size && sourcePosition < sample.pcm.lastIndex) {
                val sourceIndex = sourcePosition.toInt()
                val fraction = sourcePosition - sourceIndex
                val current = sample.pcm[sourceIndex]
                val next = sample.pcm[sourceIndex + 1]
                val interpolated = current + (next - current) * fraction
                val fadeIn = (outputIndex - startSample).coerceAtMost(256) / 256.0
                mix[outputIndex] += interpolated * velocity * fadeIn
                sourcePosition += sourceStep
                outputIndex++
            }
        }

        fun addChord(startSeconds: Double, rootMidi: Int, minor: Boolean, downStroke: Boolean, velocity: Double) {
            val intervals = intArrayOf(0, 7, 12, if (minor) 15 else 16, 19)
            val order = if (downStroke) intervals.indices else intervals.indices.reversed()
            order.forEachIndexed { strumIndex, noteIndex ->
                val start = ((startSeconds + strumIndex * 0.028) * sampleRate).toInt()
                addSampledNote(start, rootMidi + intervals[noteIndex], velocity * (1.0 - strumIndex * 0.07))
            }
        }

        val progressions = listOf(
            intArrayOf(0, 7, 9, 5),
            intArrayOf(0, 5, 7, 3),
            intArrayOf(9, 5, 0, 7),
            intArrayOf(0, 3, 5, 7)
        )
        val progression = progressions[abs(prompt.hashCode()) % progressions.size]
        val minor = prompt.contains("minor", ignoreCase = true) || prompt.contains("минор", ignoreCase = true)
        val baseRootMidi = if (prompt.contains("бас", ignoreCase = true)) 45 else 50
        val beatSeconds = 0.62
        var time = 0.0
        var beat = 0

        while (time < lengthSeconds) {
            val rootMidi = baseRootMidi + progression[(beat / 2) % progression.size]
            addSampledNote((time * sampleRate).toInt(), rootMidi - 12, 0.34)
            addChord(time + 0.035, rootMidi, minor, beat % 2 == 0, if (beat % 4 == 0) 0.52 else 0.42)
            if (beat % 2 == 1) {
                addSampledNote(((time + beatSeconds * 0.52) * sampleRate).toInt(), rootMidi + if (minor) 15 else 16, 0.30)
            }
            time += beatSeconds
            beat++
        }

        val peak = mix.maxOfOrNull { kotlin.math.abs(it) }?.coerceAtLeast(0.001) ?: 1.0
        val samples = ShortArray(totalSamples) { index ->
            val softened = kotlin.math.tanh(mix[index] / peak * 1.35) * 0.86
            (softened * Short.MAX_VALUE).toInt().toShort()
        }
        writeWavFile(audioFile, samples, sampleRate)
        return audioFile
    }

    suspend fun createOfflineArrangementOnIo(prompt: String): File = withContext(Dispatchers.IO) {
        createOfflineArrangement(prompt, duration.coerceIn(5, 30))
    }

    DisposableEffect(Unit) {
        onDispose {
            generationJob?.cancel()
            stopGeneratedPlayback()
        }
    }

    // ── Функция генерации ──
    fun generateMusic() {
        if (isGenerating) return

        if (melodyPrompt.isBlank()) {
            status = "Опишите мелодию"
            return
        }

        isGenerating = true
        status = "Генерация через AI... Это может занять 30-60 секунд"
        audioFilePath = null

        generationJob = scope.launch {
            try {
                val api = HuggingFaceService.create()

                // Формируем промпт
                val fullPrompt = "acoustic guitar, folk style, melodic: $melodyPrompt"

                // Конвертируем секунды в токены (примерно 32 токена = 1 секунда)
                val tokens = duration * 32

                val request = MusicGenRequest(
                    inputs = fullPrompt,
                    parameters = MusicGenParameters(
                        max_new_tokens = tokens,
                        do_sample = true,
                        temperature = 1.0f
                    )
                )

                withContext(Dispatchers.IO) {
                    val response = api.generateMusic(request)
                    val body = response.body()
                    val contentType = body?.contentType()?.toString().orEmpty()

                    if (!response.isSuccessful || body == null) {
                        throw IllegalStateException("AI сервис недоступен (${response.code()})")
                    }

                    if (!contentType.startsWith("audio/") && contentType.isNotBlank()) {
                        throw IllegalStateException("AI вернул не аудио: $contentType")
                    }

                    // Сохраняем WAV файл в папку приложения, доступную без разрешений.
                    val musicDir = context.getExternalFilesDir(Environment.DIRECTORY_MUSIC) ?: context.filesDir
                    val audioFile = File(musicDir, "generated_${System.currentTimeMillis()}.wav")
                    audioFile.outputStream().use { output ->
                        body.byteStream().copyTo(output)
                    }

                    withContext(Dispatchers.Main) {
                        stopGeneratedPlayback()
                        audioFilePath = audioFile.absolutePath
                        status = "Готово! Трек сгенерирован (${audioFile.length() / 1024} KB)"
                    }
                }

            } catch (e: CancellationException) {
                status = "Генерация отменена"
            } catch (e: Exception) {
                try {
                    val fallbackFile = createOfflineArrangementOnIo(melodyPrompt)
                    stopGeneratedPlayback()
                    audioFilePath = fallbackFile.absolutePath
                    status = "AI сейчас недоступен. Создан офлайн-эскиз (${fallbackFile.length() / 1024} KB)"
                } catch (fallbackError: Exception) {
                    status = "Ошибка генерации: ${e.message ?: fallbackError.message}"
                }
            } finally {
                isGenerating = false
                generationJob = null
            }
        }
    }

    fun cancelGeneration() {
        generationJob?.cancel()
        generationJob = null
        isGenerating = false
        status = "Генерация отменена"
    }

    // ═══════════════ UI ═══════════════

    Column(
        Modifier
            .fillMaxSize()
            .padding(16.dp)
            .verticalScroll(rememberScrollState())
    ) {
        Text(
            "AI Аранжировщик",
            style = MaterialTheme.typography.headlineMedium,
            color = Color.White
        )
        Text(
            "Опишите мелодию — получите трек через бесплатный AI (Hugging Face)",
            style = MaterialTheme.typography.bodyMedium,
            color = Color.Gray
        )

        Spacer(modifier = Modifier.height(20.dp))

        // ─── Описание мелодии ───
        OutlinedTextField(
            value = melodyPrompt,
            onValueChange = { melodyPrompt = it },
            label = { Text("Опишите мелодию") },
            modifier = Modifier
                .fillMaxWidth()
                .height(120.dp),
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = MaterialTheme.colorScheme.primary,
                focusedLabelColor = MaterialTheme.colorScheme.primary,
                cursorColor = Color.White,
                focusedTextColor = Color.White,
                unfocusedTextColor = Color.White
            ),
            placeholder = { Text("Например: Спокойная акустическая гитара, фолк, минорная мелодия") }
        )

        Spacer(modifier = Modifier.height(16.dp))

        // ─── Длительность ───
        Card(
            modifier = Modifier.fillMaxWidth(),
            colors = CardDefaults.cardColors(containerColor = Color(0xFF2C3E50)),
            shape = RoundedCornerShape(12.dp)
        ) {
            Column(Modifier.padding(16.dp)) {
                Text(
                    "Длительность: $duration сек",
                    style = MaterialTheme.typography.titleSmall,
                    color = Color.White,
                    fontWeight = FontWeight.Bold
                )
                Spacer(modifier = Modifier.height(8.dp))
                Slider(
                    value = duration.toFloat(),
                    onValueChange = { duration = it.toInt() },
                    valueRange = 5f..30f,
                    steps = 24,
                    colors = SliderDefaults.colors(
                        thumbColor = MaterialTheme.colorScheme.primary,
                        activeTrackColor = MaterialTheme.colorScheme.primary
                    )
                )
                Text(
                    "Рекомендуется 8-15 секунд для быстрой генерации",
                    style = MaterialTheme.typography.bodySmall,
                    color = Color.Gray
                )
            }
        }

        Spacer(modifier = Modifier.height(20.dp))

        // ─── Кнопка генерации ───
        Button(
            onClick = {
                focusManager.clearFocus()
                generateMusic()
            },
            enabled = !isGenerating,
            modifier = Modifier.fillMaxWidth(),
            colors = ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary)
        ) {
            Text(if (isGenerating) "Генерация..." else "Сгенерировать трек")
        }

        // ─── Кнопка отмены ───
        if (isGenerating) {
            Spacer(modifier = Modifier.height(8.dp))
            Button(
                onClick = { cancelGeneration() },
                modifier = Modifier.fillMaxWidth(),
                colors = ButtonDefaults.buttonColors(containerColor = Color.Red)
            ) {
                Text("Отменить генерацию")
            }
        }

        Spacer(modifier = Modifier.height(16.dp))

        // ─── Статус ───
        if (status.isNotEmpty()) {
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(
                    containerColor = if (audioFilePath != null) Color(0xFF2ECC71) else Color(0xFF2C3E50)
                ),
                shape = RoundedCornerShape(12.dp)
            ) {
                Text(
                    status,
                    modifier = Modifier.padding(16.dp),
                    color = Color.White,
                    style = MaterialTheme.typography.bodyMedium
                )
            }
        }

        audioFilePath?.let { path ->
            Spacer(modifier = Modifier.height(12.dp))
            Button(
                onClick = {
                    focusManager.clearFocus()
                    playGeneratedTrack(path)
                },
                modifier = Modifier.fillMaxWidth()
            ) {
                Text(if (isPlayingGenerated) "Остановить" else "Воспроизвести")
            }
        }

        // ─── Результат ───
        audioFilePath?.let { path ->
            Spacer(modifier = Modifier.height(12.dp))
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = Color(0xFF34495E)),
                shape = RoundedCornerShape(12.dp)
            ) {
                Column(Modifier.padding(16.dp)) {
                    Text(
                        "Трек готов!",
                        fontSize = 18.sp,
                        fontWeight = FontWeight.Bold,
                        color = Color(0xFF2ECC71)
                    )
                    Spacer(modifier = Modifier.height(8.dp))
                    Text(
                        "Файл: ${File(path).name}",
                        style = MaterialTheme.typography.bodySmall,
                        color = Color.Gray
                    )
                }
            }
        }

        Spacer(modifier = Modifier.height(16.dp))

        // ─── Информация ───
        Text(
            "💡 Совет: Чем короче трек, тем быстрее генерация",
            style = MaterialTheme.typography.bodySmall,
            color = Color.Gray
        )
        Spacer(modifier = Modifier.height(8.dp))
        Text(
            "🆓 Полностью бесплатно через Hugging Face AI",
            style = MaterialTheme.typography.bodySmall,
            color = Color(0xFF2ECC71)
        )
        Spacer(modifier = Modifier.height(120.dp))
    }
}
